is_production = false

[network]
# This must be 0.0.0.0 if you are hosting via Docker (recommended)
host = "0.0.0.0"
# I think for Kestrel by default we will allocate ports 5180-5189 to us.
# I see no reason to allocate more than those 10 ports for my current plans.
# - Stribes
ports = { gateway = 5180, api = 5181 }

[network.cors]
allowed_origins = ["*"]
allow_credentials = true

[database]
postgres = "postgresql://kestrel:kestrel@postgres:5432/kestrel"

[api.registration]
minimum_age = 16
